### ISSUE TITLE
Deployment Instructions

### ISSUE THREAD

**Issue by 2ndtlmining** [RunOnFlux/ssp-wallet#49]
Fantastic that there is an open source wallet we can use. Any chance when the Cypherpunk dust settles you could help the lesser technical people with deployment instructions on how to use it please?

**Comment by TheTrunk** [comment]
Hi, to operate SSP you need 2 components
- SSP Wallet (this repository, wallet)
- SSP Key (https://github.com/RunOnFlux/ssp-key, 2nd factor authentiaction key)

Usually you can go to Actions and take the latest artifact from both wallet and key.
Here is some showcase video of how to set it up:
https://www.youtube.com/watch?v=o4IOvFI6bcg&t=2432s&ab_channel=FluxLabs

We are now undergoing internal testing with a goal of open testing in early January. That time we will post a nice guide with actual play store/app store/chrome store download links.
